#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionsMenu

#include "../SDK/Basic.hpp"

#include "WBP_OptionsMenu_classes.hpp"
#include "WBP_OptionsMenu_parameters.hpp"


namespace SDK
{

// Function WBP_OptionsMenu.WBP_OptionsMenu_C.SetDLLCommitVersion
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString&                          NewVersion                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)

void UWBP_OptionsMenu_C::SetDLLCommitVersion(class FString& NewVersion)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "SetDLLCommitVersion");

	Params::WBP_OptionsMenu_C_SetDLLCommitVersion Parms{};

	Parms.NewVersion = std::move(NewVersion);

	UObject::ProcessEvent(Func, &Parms);

	NewVersion = std::move(Parms.NewVersion);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.OnButtonClicked_PlaySFX
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_OptionsMenu_C::OnButtonClicked_PlaySFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "OnButtonClicked_PlaySFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.SetOnlineStatus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsOnline                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_OptionsMenu_C::SetOnlineStatus(bool bIsOnline)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "SetOnlineStatus");

	Params::WBP_OptionsMenu_C_SetOnlineStatus Parms{};

	Parms.bIsOnline = bIsOnline;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.ToggleVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_OptionsMenu_C::ToggleVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "ToggleVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.bVisibilityToESlate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility*                       Visibility_0                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_OptionsMenu_C::bVisibilityToESlate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "bVisibilityToESlate");

	Params::WBP_OptionsMenu_C_bVisibilityToESlate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.OutVisibility;
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.GetDominatingTickRate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_OptionsMenu_C::GetDominatingTickRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "GetDominatingTickRate");

	Params::WBP_OptionsMenu_C_GetDominatingTickRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.DominatingTickRate;
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.GetInputKey
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FKey*                            InputKey_0                                             (Parm, OutParm, HasGetValueTypeHash)

FKey UWBP_OptionsMenu_C::GetInputKey() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "GetInputKey");

	Params::WBP_OptionsMenu_C_GetInputKey Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.OutputKey;
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.IsMenuVisible
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Bool                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

bool UWBP_OptionsMenu_C::IsMenuVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "IsMenuVisible");

	Params::WBP_OptionsMenu_C_IsMenuVisible Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.Bool;
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.SetInputKey
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FKey&                      NewKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_OptionsMenu_C::SetInputKey(const struct FKey& NewKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "SetInputKey");

	Params::WBP_OptionsMenu_C_SetInputKey Parms{};

	Parms.NewKey = std::move(NewKey);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.OnFailure_C64D486E4E489CADFC32FC91E18DF130
// (BlueprintCallable, BlueprintEvent)

void UWBP_OptionsMenu_C::OnFailure_C64D486E4E489CADFC32FC91E18DF130()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "OnFailure_C64D486E4E489CADFC32FC91E18DF130");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.OnSuccess_C64D486E4E489CADFC32FC91E18DF130
// (BlueprintCallable, BlueprintEvent)

void UWBP_OptionsMenu_C::OnSuccess_C64D486E4E489CADFC32FC91E18DF130()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "OnSuccess_C64D486E4E489CADFC32FC91E18DF130");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_OptionsMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "PreConstruct");

	Params::WBP_OptionsMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_OptionsMenu_C::BndEvt__SettingsButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "BndEvt__SettingsButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.InternalTick
// (BlueprintCallable, BlueprintEvent)

void UWBP_OptionsMenu_C::InternalTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "InternalTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.BndEvt__ReturnToMainMenuButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_OptionsMenu_C::BndEvt__ReturnToMainMenuButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "BndEvt__ReturnToMainMenuButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.BndEvt__QuitGameButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_OptionsMenu_C::BndEvt__QuitGameButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "BndEvt__QuitGameButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.BndEvt__Start_OR_StopHostingButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_OptionsMenu_C::BndEvt__Start_OR_StopHostingButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "BndEvt__Start_OR_StopHostingButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.BndEvt__ResumeButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_OptionsMenu_C::BndEvt__ResumeButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "BndEvt__ResumeButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionsMenu_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "Tick");

	Params::WBP_OptionsMenu_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_OptionsMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionsMenu.WBP_OptionsMenu_C.ExecuteUbergraph_WBP_OptionsMenu
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionsMenu_C::ExecuteUbergraph_WBP_OptionsMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionsMenu_C", "ExecuteUbergraph_WBP_OptionsMenu");

	Params::WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

