#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AJBTitleScreen

#include "../SDK/Basic.hpp"

#include "WBP_AJBTitleScreen_classes.hpp"
#include "WBP_AJBTitleScreen_parameters.hpp"


namespace SDK
{

// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.SetDLLCommitVersion
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    NewVersion                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_AJBTitleScreen_C::SetDLLCommitVersion(const class FString& NewVersion)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "SetDLLCommitVersion");

	Params::WBP_AJBTitleScreen_C_SetDLLCommitVersion Parms{};

	Parms.NewVersion = std::move(NewVersion);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.OnButtonPressed
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_AJBTitleScreen_C::OnButtonPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "OnButtonPressed");

	UObject::ProcessEvent(Func, nullptr);
}

// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_AJBTitleScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.ExecuteUbergraph_WBP_AJBTitleScreen
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AJBTitleScreen_C::ExecuteUbergraph_WBP_AJBTitleScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "ExecuteUbergraph_WBP_AJBTitleScreen");

	Params::WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.BndEvt__BT_YouTube_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_AJBTitleScreen_C::BndEvt__BT_YouTube_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "BndEvt__BT_YouTube_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.BndEvt__BT_TBD_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_AJBTitleScreen_C::BndEvt__BT_TBD_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "BndEvt__BT_TBD_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.BndEvt__BT_InvisiblePressToStart_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_AJBTitleScreen_C::BndEvt__BT_InvisiblePressToStart_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "BndEvt__BT_InvisiblePressToStart_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.BndEvt__BT_GitHub_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_AJBTitleScreen_C::BndEvt__BT_GitHub_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "BndEvt__BT_GitHub_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.BndEvt__BT_Discord_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_AJBTitleScreen_C::BndEvt__BT_Discord_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AJBTitleScreen_C", "BndEvt__BT_Discord_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

