#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AJBTitleScreen

#include "../SDK/Basic.hpp"


namespace SDK::Params
{

// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.SetDLLCommitVersion
// 0x0028 (0x0028 - 0x0000)
struct WBP_AJBTitleScreen_C_SetDLLCommitVersion final
{
public:
	class FString                                 NewVersion;                                        // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0010(0x0018)()
};
static_assert(alignof(WBP_AJBTitleScreen_C_SetDLLCommitVersion) == 0x000008, "Wrong alignment on WBP_AJBTitleScreen_C_SetDLLCommitVersion");
static_assert(sizeof(WBP_AJBTitleScreen_C_SetDLLCommitVersion) == 0x000028, "Wrong size on WBP_AJBTitleScreen_C_SetDLLCommitVersion");
static_assert(offsetof(WBP_AJBTitleScreen_C_SetDLLCommitVersion, NewVersion) == 0x000000, "Member 'WBP_AJBTitleScreen_C_SetDLLCommitVersion::NewVersion' has a wrong offset!");
static_assert(offsetof(WBP_AJBTitleScreen_C_SetDLLCommitVersion, CallFunc_Conv_StringToText_ReturnValue) == 0x000010, "Member 'WBP_AJBTitleScreen_C_SetDLLCommitVersion::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function WBP_AJBTitleScreen.WBP_AJBTitleScreen_C.ExecuteUbergraph_WBP_AJBTitleScreen
// 0x0004 (0x0004 - 0x0000)
struct WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen) == 0x000004, "Wrong alignment on WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen");
static_assert(sizeof(WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen) == 0x000004, "Wrong size on WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen");
static_assert(offsetof(WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen, EntryPoint) == 0x000000, "Member 'WBP_AJBTitleScreen_C_ExecuteUbergraph_WBP_AJBTitleScreen::EntryPoint' has a wrong offset!");

}

