#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CallbackTimerHandler

#include "../SDK/Basic.hpp"

#include "WBP_CallbackTimerHandler_classes.hpp"
#include "WBP_CallbackTimerHandler_parameters.hpp"


namespace SDK
{

// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.addToArrays
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   fWaitFor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   pUpper                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   pLower                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_CallbackTimerHandler_C::AddToArrays(float fWaitFor, int32 pUpper, int32 pLower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "AddToArrays");

	Params::WBP_CallbackTimerHandler_C_addToArrays Parms{};

	Parms.fWaitFor = fWaitFor;
	Parms.pUpper = pUpper;
	Parms.pLower = pLower;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.OutIndex;
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.removeFromArrays
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_CallbackTimerHandler_C::RemoveFromArrays(int32 Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "RemoveFromArrays");

	Params::WBP_CallbackTimerHandler_C_removeFromArrays Parms{};

	Parms.Index = Index;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.OutIndex;
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.SetCallbackTimer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   fWaitFor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   pCallbackUpper                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   pCallbackLower                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CallbackTimerHandler_C::SetCallbackTimer(float fWaitFor, int32 pCallbackUpper, int32 pCallbackLower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "SetCallbackTimer");

	Params::WBP_CallbackTimerHandler_C_SetCallbackTimer Parms{};

	Parms.fWaitFor = fWaitFor;
	Parms.pCallbackUpper = pCallbackUpper;
	Parms.pCallbackLower = pCallbackLower;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CallbackTimerHandler_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.InternalTick
// (BlueprintCallable, BlueprintEvent)

void UWBP_CallbackTimerHandler_C::InternalTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "InternalTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.TimerTick
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32&                            ArrayIndex                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CallbackTimerHandler_C::TimerTick(const int32& ArrayIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "TimerTick");

	Params::WBP_CallbackTimerHandler_C_TimerTick Parms{};

	Parms.ArrayIndex = ArrayIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.ExecuteUbergraph_WBP_CallbackTimerHandler
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CallbackTimerHandler_C::ExecuteUbergraph_WBP_CallbackTimerHandler(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "ExecuteUbergraph_WBP_CallbackTimerHandler");

	Params::WBP_CallbackTimerHandler_C_ExecuteUbergraph_WBP_CallbackTimerHandler Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CallbackTimerHandler.WBP_CallbackTimerHandler_C.CacheMaterial
// (Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UMaterial*                        MaterialToCache                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CallbackTimerHandler_C::CacheMaterial(class UMaterial* MaterialToCache) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CallbackTimerHandler_C", "CacheMaterial");

	Params::WBP_CallbackTimerHandler_C_CacheMaterial Parms{};

	Parms.MaterialToCache = MaterialToCache;

	UObject::ProcessEvent(Func, &Parms);
}

}

